### ISSUE TITLE
Casandra data load

### ISSUE THREAD

**Issue by wraithking** [DitaGabalina/devops_db_group#10]
Create a mechanism from where Casandra will get demo data ( from web, or csv will be copied from repo. Discuss in team) 
Load this data to Casandra. 

Tip: It can be done by Ansible.

**Comment by whyme35** [comment]
• Added a playbook for loading creating data model and loading data in main Cassandra node using shell and cql scripts provided by DitaGablina
• Added Playbook execution in terraform for automated deployment
• Fixed typos in hosts template
