### ISSUE TITLE
Branching strategy

### ISSUE THREAD

**Issue by wraithking** [DitaGabalina/devops_db_group#13]
Create what Branching strategy you will use 
where it will be defined 

Tip: in wiki I think ;)

**Comment by whyme35** [comment]
I recommend using feature branching strategy based on Github Flow. Feature branches would be used for feature developments and bug fixes, but mater branch should always be production ready. When a feature is developed lets make and review a pull request and merge it in main branch. More on Github Flow: https://docs.github.com/en/get-started/quickstart/github-flow

**Comment by whyme35** [comment]
Izveidoju Wiki zarošanas stratēģijai.
https://github.com/DitaGabalina/devops_db_group/wiki/Zaro%C5%A1anas-strat%C4%93%C4%A3ija
