### ISSUE TITLE
Create naming convention

### ISSUE THREAD

**Issue by wraithking** [DitaGabalina/devops_db_group#14]
Define what naming convention for resources in AWS and in code you will use. Where you will define it? 

Tip: In wiki I think ;) 

https://github.com/osodevops/aws-enterprise-naming-tagging-standard

**Comment by whyme35** [comment]
Closing this as naming convention already created in wiki, at:
https://github.com/DitaGabalina/devops_db_group/wiki/Nosaukumu-veido%C5%A1anas-principi
